### ISSUE TITLE
Feat/Ques: way to create archive and binary both?

### ISSUE THREAD

**Issue by pratikbalar** [crazy-max/goreleaser-xx#69]
Hello @crazy-max Thanks for amazing project,

Just wanted to ask you that is there anyway to output/generate archive as well as binary both in single command? Which means specifying multiple `--artifact-type`

**Comment by crazy-max** [comment]
#70 should fix it

**Comment by pratikbalar** [comment]
Thank you. Again.

**Comment by crazy-max** [comment]
I changed the behavior to handle that with multi flags `--artifacts=archive --artifacts=bin` in #72
